server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG



spring:
  messages:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  security:
    user:
      name: username
      password: robbins4bos
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

